### ISSUE TITLE
phonegap 2.9 build error

### ISSUE THREAD

**Issue by bau720123** [sampathpremarathna/ContactPickerUtil#1]
when I build by Dreamweaver CC with phonegap 2.9
every platform have this wrong message
plugin unsupported: com.mobitel.nalaka.piccon

I tried put this code to my config.xml
Usage Instructions = > https://build.phonegap.com/plugins/39
but the same...

**Comment by sampathpremarathna** [comment]
Thank you for information

Please change the plugin values to com.mobitel.nalaka.piccon.ContactPick and check again.

**Comment by bau720123** [comment]
the same too...
wrong message...
plugin unsupported: com.mobitel.nalaka.piccon.contactpick

**Comment by bau720123** [comment]
Just tested once again
The same situation

**Comment by sampathpremarathna** [comment]
It seems there are some problems.I am working on it and doing the
modifications.
thanks.

On Tue, Aug 27, 2013 at 7:56 AM, bau720123 notifications@github.com wrote:

> Just tested once again
> The same situation
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sampathpremarathna/ContactPickerUtil/issues/1#issuecomment-23309304
> .

## 

_~sampathpremarathna~_

**Comment by bau720123** [comment]
now is OK
Thanks
