### ISSUE TITLE
no method 'contactPickerUtil' error message

### ISSUE THREAD

**Issue by bau720123** [sampathpremarathna/ContactPickerUtil#2]
I am in phonegap build 2.9
And I use your code as same as your example
But when I run the javascript in chrome browser
it appears a wrong message
Uncaught TypeError: Object [object global] has no method 'contactPickerUtil'

Of course, the real phone is also performed is also not work

**Comment by sampathpremarathna** [comment]
Hi all,

I found there is a problem and hopefully found a solution also. I have made a mistake(put incorrect name for the plugin name.) when binding the plugin. For now what you have to do is just skip adding the ContactPicker.js file to the page and add following to your page.

 window.contactPickerUtil = function(callback) {
                cordova.exec(callback, function(err) {
                    console.log(err);
                }, "ContactPickerUtil", "pick", []);
  };

After that you can normally call that function as i explained in the doc.I will update the code soon and sorry for the inconvenience.

**Comment by bau720123** [comment]
now is OK
Thanks
