### ISSUE TITLE
Cordova supports this functionality by default now

### ISSUE THREAD

**Issue by ChrisAntaki** [sampathpremarathna/ContactPickerUtil#7]
https://github.com/apache/cordova-plugin-contacts/blob/master/doc/index.md

**Comment by sampathpremarathna** [comment]
ah ha finally they do :)

On Sat, Oct 25, 2014 at 3:50 PM, Chris Antaki notifications@github.com
wrote:

> https://github.com/apache/cordova-plugin-contacts/blob/master/doc/index.md
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sampathpremarathna/ContactPickerUtil/issues/7.

## 

_~sampathpremarathna~_

**Comment by ChrisAntaki** [comment]
:smile:
